# Generated by Django 5.0.6 on 2024-05-17 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='quantity',
        ),
    ]
