# Generated by Django 5.0.6 on 2024-05-18 06:30

import cloudinary.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_productmodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
