# Generated by Django 5.0.6 on 2024-05-24 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_saledetailmodel_sale_id_usuariomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemodel',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
