# Generated by Django 5.0.6 on 2024-05-24 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_salemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salemodel',
            name='user',
        ),
    ]
